create database bank;
use bank;
select * from accounts;
select * from customers;
select * from loans;
select * from transactions;


-- Q1: Write a query to display all customer details present in the bank database.
SELECT * FROM customers;

-- Q2: Write a query to count the total number of customers in the bank.
SELECT COUNT(*) AS total_customers FROM customers;

-- Q3: Write a query to display all account records with their balances.
SELECT * FROM accounts;

-- Q4: Write a query to show all transaction records available in the system.
SELECT * FROM transactions;

-- Q5: Write a query to find distinct cities where customers belong.
SELECT DISTINCT city FROM customers;

-- Q6: Write a query to calculate the total number of accounts in the bank.
SELECT COUNT(*) AS total_accounts FROM accounts;

-- Q7: Write a query to find the minimum and maximum account balance.
SELECT MIN(balance) AS minimum_balance,
       MAX(balance) AS maximum_balance
FROM accounts;

-- Q8: Write a query to calculate total loan applications in the bank.
SELECT COUNT(*) AS total_loan_applications FROM loans;

-- Q9: Write a query to find the total balance held by each customer across all accounts.
SELECT customer_id,
       SUM(balance) AS total_balance
FROM accounts
GROUP BY customer_id;

-- Q10: Write a query to calculate total number of transactions performed by each account.
SELECT account_id,
       COUNT(transaction_id) AS total_transactions
FROM transactions
GROUP BY account_id;

-- Q11: Write a query to analyze credit and debit transaction amounts separately.
SELECT transaction_type,
       SUM(amount) AS total_amount
FROM transactions
GROUP BY transaction_type;

-- Q12: Write a query to find the average transaction amount in the bank.
SELECT AVG(amount) AS average_transaction_amount
FROM transactions;

-- Q13: Write a query to display city-wise total number of customers.
SELECT city,
       COUNT(customer_id) AS total_customers
FROM customers
GROUP BY city;

-- Q14: Write a query to identify customers who have taken at least one loan.
SELECT DISTINCT customer_id
FROM loans;

-- Q15: Write a query to find accounts that have performed only credit transactions.
SELECT account_id
FROM transactions
GROUP BY account_id
HAVING SUM(CASE WHEN transaction_type = 'Debit' THEN 1 ELSE 0 END) = 0;

-- Q16: Write a query to calculate total revenue generated by transactions.
SELECT SUM(amount) AS total_revenue
FROM transactions;

-- Q17: Write a query to find customers with balance greater than average bank balance.
SELECT customer_id,
       SUM(balance) AS total_balance
FROM accounts
GROUP BY customer_id
HAVING SUM(balance) > (SELECT AVG(balance) FROM accounts);

-- Q18: Write a query to identify top 5 customers with highest total bank balance.
SELECT customer_id,
       SUM(balance) AS total_balance
FROM accounts
GROUP BY customer_id
ORDER BY total_balance DESC
LIMIT 5;

-- Q19: Write a query to find the most active customers based on transaction count.
SELECT a.customer_id,
       COUNT(t.transaction_id) AS total_transactions
FROM accounts a
JOIN transactions t ON a.account_id = t.account_id
GROUP BY a.customer_id
ORDER BY total_transactions DESC;

-- Q20: Write a query to detect suspicious transactions where debit amount exceeds 4000.
SELECT *
FROM transactions
WHERE transaction_type = 'Debit'
AND amount > 4000;

-- Q21: Write a query to find customers who have no loan history at all.
SELECT c.customer_id, c.name
FROM customers c
LEFT JOIN loans l ON c.customer_id = l.customer_id
WHERE l.customer_id IS NULL;

-- Q22: Write a query to analyze loan status distribution across the bank.
SELECT status,
       COUNT(loan_id) AS total_loans
FROM loans
GROUP BY status;

-- Q23: Write a query to find city-wise total banking power (total balance).
SELECT c.city,
       SUM(a.balance) AS total_bank_balance
FROM customers c
JOIN accounts a ON c.customer_id = a.customer_id
GROUP BY c.city;

-- Q24: Write a query to detect dormant accounts with zero debit transactions.
SELECT account_id
FROM transactions
GROUP BY account_id
HAVING SUM(CASE WHEN transaction_type = 'Debit' THEN 1 ELSE 0 END) = 0;

-- Q25: Write a query to find customers who have both loan and low balance (<5000).
SELECT c.customer_id, c.name
FROM customers c
JOIN accounts a ON c.customer_id = a.customer_id
JOIN loans l ON c.customer_id = l.customer_id
GROUP BY c.customer_id
HAVING SUM(a.balance) < 5000;

-- Q26: Write a query to rank customers based on their total financial activity.
SELECT customer_id,
       SUM(balance) AS total_balance,
       RANK() OVER (ORDER BY SUM(balance) DESC) AS customer_rank
FROM accounts
GROUP BY customer_id;

-- Q27: Write a query to calculate monthly transaction trends (if date available).
SELECT DATE_FORMAT(transaction_date, '%Y-%m') AS transaction_month,
       COUNT(transaction_id) AS total_transactions
FROM transactions
GROUP BY transaction_month;

-- Q28: Write a query to find accounts with highest single transaction value.
SELECT MAX(amount) AS highest_transaction_value
FROM transactions;

-- Q29: Write a query to identify high-risk loan customers (pending/rejected + low balance).
SELECT c.customer_id,
       c.name,
       l.status,
       SUM(a.balance) AS total_balance
FROM customers c
JOIN loans l ON c.customer_id = l.customer_id
JOIN accounts a ON c.customer_id = a.customer_id
GROUP BY c.customer_id
HAVING l.status IN ('Pending', 'Rejected')
AND SUM(a.balance) < 5000;

-- Q30: Write a query to compute overall bank liquidity (total balance vs loans).
SELECT
    (SELECT SUM(balance) FROM accounts) AS total_bank_deposits,
    (SELECT SUM(loan_amount) FROM loans) AS total_loans,
    (SELECT SUM(balance) FROM accounts) - (SELECT SUM(loan_amount) FROM loans)  AS liquidity;

-- Q31: Write a query to display customer details along with their account information.
SELECT c.customer_id, c.name, a.account_id, a.account_type, a.balance
FROM customers c
JOIN accounts a ON c.customer_id = a.customer_id;

-- Q32: Write a query to display customer details along with their loan information.
SELECT c.customer_id, c.name, l.loan_id, l.loan_amount, l.status
FROM customers c
JOIN loans l ON c.customer_id = l.customer_id;

-- Q33: Write a query to display account details along with all related transactions.
SELECT a.account_id, t.transaction_id, t.amount, t.transaction_type, t.transaction_date
FROM accounts a
JOIN transactions t ON a.account_id = t.account_id;

-- Q34: Write a query to display complete banking overview including customers, accounts and loans.
SELECT c.customer_id, c.name, a.account_type, a.balance, l.loan_amount, l.status
FROM customers c
LEFT JOIN accounts a ON c.customer_id = a.customer_id
LEFT JOIN loans l ON c.customer_id = l.customer_id;

-- Q35: Write a query to create a view for customer summary with total balance.
CREATE VIEW customer_summary AS
SELECT c.customer_id, c.name, c.city,
       SUM(a.balance) AS total_balance
FROM customers c
JOIN accounts a ON c.customer_id = a.customer_id
GROUP BY c.customer_id, c.name, c.city;

-- Q36: Write a query to create a view for transaction summary per account.
CREATE VIEW transaction_summary AS
SELECT account_id,
       COUNT(*) AS total_transactions,
       SUM(amount) AS total_amount
FROM transactions
GROUP BY account_id;